/** Every country's short name — used to give Person/Organization location
 * filters a real list to pick from instead of free typing. `label` is
 * shown in Lithuanian; `value` is the English name Apollo's API actually
 * expects (its global database is matched in English regardless of UI
 * language) — never translate `value`, only `label`. Apollo's own
 * location filters accept plain city/state/country strings, so `value` is
 * passed through exactly as written here — no separate country-code
 * mapping needed. */
export const COUNTRIES: Array<{ label: string; value: string }> = [
  { label: 'Afganistanas', value: 'Afghanistan' },
  { label: 'Albanija', value: 'Albania' },
  { label: 'Alžyras', value: 'Algeria' },
  { label: 'Andora', value: 'Andorra' },
  { label: 'Angola', value: 'Angola' },
  { label: 'Antigva ir Barbuda', value: 'Antigua and Barbuda' },
  { label: 'Argentina', value: 'Argentina' },
  { label: 'Armėnija', value: 'Armenia' },
  { label: 'Australija', value: 'Australia' },
  { label: 'Austrija', value: 'Austria' },
  { label: 'Azerbaidžanas', value: 'Azerbaijan' },
  { label: 'Bahamos', value: 'Bahamas' },
  { label: 'Bahreinas', value: 'Bahrain' },
  { label: 'Bangladešas', value: 'Bangladesh' },
  { label: 'Barbadosas', value: 'Barbados' },
  { label: 'Baltarusija', value: 'Belarus' },
  { label: 'Belgija', value: 'Belgium' },
  { label: 'Belizas', value: 'Belize' },
  { label: 'Beninas', value: 'Benin' },
  { label: 'Butanas', value: 'Bhutan' },
  { label: 'Bolivija', value: 'Bolivia' },
  { label: 'Bosnija ir Hercegovina', value: 'Bosnia and Herzegovina' },
  { label: 'Botsvana', value: 'Botswana' },
  { label: 'Brazilija', value: 'Brazil' },
  { label: 'Brunėjus', value: 'Brunei' },
  { label: 'Bulgarija', value: 'Bulgaria' },
  { label: 'Burkina Fasas', value: 'Burkina Faso' },
  { label: 'Burundis', value: 'Burundi' },
  { label: 'Žaliasis Kyšulys', value: 'Cabo Verde' },
  { label: 'Kambodža', value: 'Cambodia' },
  { label: 'Kamerūnas', value: 'Cameroon' },
  { label: 'Kanada', value: 'Canada' },
  { label: 'Centrinės Afrikos Respublika', value: 'Central African Republic' },
  { label: 'Čadas', value: 'Chad' },
  { label: 'Čilė', value: 'Chile' },
  { label: 'Kinija', value: 'China' },
  { label: 'Kolumbija', value: 'Colombia' },
  { label: 'Komorai', value: 'Comoros' },
  { label: 'Kongas', value: 'Congo' },
  { label: 'Kosta Rika', value: 'Costa Rica' },
  { label: 'Kroatija', value: 'Croatia' },
  { label: 'Kuba', value: 'Cuba' },
  { label: 'Kipras', value: 'Cyprus' },
  { label: 'Čekija', value: 'Czechia' },
  { label: 'Danija', value: 'Denmark' },
  { label: 'Džibutis', value: 'Djibouti' },
  { label: 'Dominika', value: 'Dominica' },
  { label: 'Dominikos Respublika', value: 'Dominican Republic' },
  { label: 'Ekvadoras', value: 'Ecuador' },
  { label: 'Egiptas', value: 'Egypt' },
  { label: 'Salvadoras', value: 'El Salvador' },
  { label: 'Pusiaujo Gvinėja', value: 'Equatorial Guinea' },
  { label: 'Eritrėja', value: 'Eritrea' },
  { label: 'Estija', value: 'Estonia' },
  { label: 'Esvatinis', value: 'Eswatini' },
  { label: 'Etiopija', value: 'Ethiopia' },
  { label: 'Fidžis', value: 'Fiji' },
  { label: 'Suomija', value: 'Finland' },
  { label: 'Prancūzija', value: 'France' },
  { label: 'Gabonas', value: 'Gabon' },
  { label: 'Gambija', value: 'Gambia' },
  { label: 'Gruzija', value: 'Georgia' },
  { label: 'Vokietija', value: 'Germany' },
  { label: 'Gana', value: 'Ghana' },
  { label: 'Graikija', value: 'Greece' },
  { label: 'Grenada', value: 'Grenada' },
  { label: 'Gvatemala', value: 'Guatemala' },
  { label: 'Gvinėja', value: 'Guinea' },
  { label: 'Bisau Gvinėja', value: 'Guinea-Bissau' },
  { label: 'Gajana', value: 'Guyana' },
  { label: 'Haitis', value: 'Haiti' },
  { label: 'Hondūras', value: 'Honduras' },
  { label: 'Vengrija', value: 'Hungary' },
  { label: 'Islandija', value: 'Iceland' },
  { label: 'Indija', value: 'India' },
  { label: 'Indonezija', value: 'Indonesia' },
  { label: 'Iranas', value: 'Iran' },
  { label: 'Irakas', value: 'Iraq' },
  { label: 'Airija', value: 'Ireland' },
  { label: 'Izraelis', value: 'Israel' },
  { label: 'Italija', value: 'Italy' },
  { label: 'Jamaika', value: 'Jamaica' },
  { label: 'Japonija', value: 'Japan' },
  { label: 'Jordanija', value: 'Jordan' },
  { label: 'Kazachstanas', value: 'Kazakhstan' },
  { label: 'Kenija', value: 'Kenya' },
  { label: 'Kiribatis', value: 'Kiribati' },
  { label: 'Kosovas', value: 'Kosovo' },
  { label: 'Kuveitas', value: 'Kuwait' },
  { label: 'Kirgizija', value: 'Kyrgyzstan' },
  { label: 'Laosas', value: 'Laos' },
  { label: 'Latvija', value: 'Latvia' },
  { label: 'Libanas', value: 'Lebanon' },
  { label: 'Lesotas', value: 'Lesotho' },
  { label: 'Liberija', value: 'Liberia' },
  { label: 'Libija', value: 'Libya' },
  { label: 'Lichtenšteinas', value: 'Liechtenstein' },
  { label: 'Lietuva', value: 'Lithuania' },
  { label: 'Liuksemburgas', value: 'Luxembourg' },
  { label: 'Madagaskaras', value: 'Madagascar' },
  { label: 'Malavis', value: 'Malawi' },
  { label: 'Malaizija', value: 'Malaysia' },
  { label: 'Maldyvai', value: 'Maldives' },
  { label: 'Malis', value: 'Mali' },
  { label: 'Malta', value: 'Malta' },
  { label: 'Maršalo Salos', value: 'Marshall Islands' },
  { label: 'Mauritanija', value: 'Mauritania' },
  { label: 'Mauricijus', value: 'Mauritius' },
  { label: 'Meksika', value: 'Mexico' },
  { label: 'Mikronezija', value: 'Micronesia' },
  { label: 'Moldova', value: 'Moldova' },
  { label: 'Monakas', value: 'Monaco' },
  { label: 'Mongolija', value: 'Mongolia' },
  { label: 'Juodkalnija', value: 'Montenegro' },
  { label: 'Marokas', value: 'Morocco' },
  { label: 'Mozambikas', value: 'Mozambique' },
  { label: 'Mianmaras', value: 'Myanmar' },
  { label: 'Namibija', value: 'Namibia' },
  { label: 'Nauru', value: 'Nauru' },
  { label: 'Nepalas', value: 'Nepal' },
  { label: 'Nyderlandai', value: 'Netherlands' },
  { label: 'Naujoji Zelandija', value: 'New Zealand' },
  { label: 'Nikaragva', value: 'Nicaragua' },
  { label: 'Nigeris', value: 'Niger' },
  { label: 'Nigerija', value: 'Nigeria' },
  { label: 'Šiaurės Korėja', value: 'North Korea' },
  { label: 'Šiaurės Makedonija', value: 'North Macedonia' },
  { label: 'Norvegija', value: 'Norway' },
  { label: 'Omanas', value: 'Oman' },
  { label: 'Pakistanas', value: 'Pakistan' },
  { label: 'Palau', value: 'Palau' },
  { label: 'Palestina', value: 'Palestine' },
  { label: 'Panama', value: 'Panama' },
  { label: 'Papua Naujoji Gvinėja', value: 'Papua New Guinea' },
  { label: 'Paragvajus', value: 'Paraguay' },
  { label: 'Peru', value: 'Peru' },
  { label: 'Filipinai', value: 'Philippines' },
  { label: 'Lenkija', value: 'Poland' },
  { label: 'Portugalija', value: 'Portugal' },
  { label: 'Kataras', value: 'Qatar' },
  { label: 'Rumunija', value: 'Romania' },
  { label: 'Rusija', value: 'Russia' },
  { label: 'Ruanda', value: 'Rwanda' },
  { label: 'Sent Kitsas ir Nevis', value: 'Saint Kitts and Nevis' },
  { label: 'Sent Lusija', value: 'Saint Lucia' },
  { label: 'Sent Vinsentas ir Grenadinai', value: 'Saint Vincent and the Grenadines' },
  { label: 'Samoa', value: 'Samoa' },
  { label: 'San Marinas', value: 'San Marino' },
  { label: 'San Tomė ir Prinsipė', value: 'Sao Tome and Principe' },
  { label: 'Saudo Arabija', value: 'Saudi Arabia' },
  { label: 'Senegalas', value: 'Senegal' },
  { label: 'Serbija', value: 'Serbia' },
  { label: 'Seišeliai', value: 'Seychelles' },
  { label: 'Siera Leonė', value: 'Sierra Leone' },
  { label: 'Singapūras', value: 'Singapore' },
  { label: 'Slovakija', value: 'Slovakia' },
  { label: 'Slovėnija', value: 'Slovenia' },
  { label: 'Saliamono Salos', value: 'Solomon Islands' },
  { label: 'Somalis', value: 'Somalia' },
  { label: 'Pietų Afrika', value: 'South Africa' },
  { label: 'Pietų Korėja', value: 'South Korea' },
  { label: 'Pietų Sudanas', value: 'South Sudan' },
  { label: 'Ispanija', value: 'Spain' },
  { label: 'Šri Lanka', value: 'Sri Lanka' },
  { label: 'Sudanas', value: 'Sudan' },
  { label: 'Surinamas', value: 'Suriname' },
  { label: 'Švedija', value: 'Sweden' },
  { label: 'Šveicarija', value: 'Switzerland' },
  { label: 'Sirija', value: 'Syria' },
  { label: 'Taivanas', value: 'Taiwan' },
  { label: 'Tadžikistanas', value: 'Tajikistan' },
  { label: 'Tanzanija', value: 'Tanzania' },
  { label: 'Tailandas', value: 'Thailand' },
  { label: 'Rytų Timoras', value: 'Timor-Leste' },
  { label: 'Togas', value: 'Togo' },
  { label: 'Tonga', value: 'Tonga' },
  { label: 'Trinidadas ir Tobagas', value: 'Trinidad and Tobago' },
  { label: 'Tunisas', value: 'Tunisia' },
  { label: 'Turkija', value: 'Turkey' },
  { label: 'Turkmenistanas', value: 'Turkmenistan' },
  { label: 'Tuvalu', value: 'Tuvalu' },
  { label: 'Uganda', value: 'Uganda' },
  { label: 'Ukraina', value: 'Ukraine' },
  { label: 'Jungtiniai Arabų Emyratai', value: 'United Arab Emirates' },
  { label: 'Jungtinė Karalystė', value: 'United Kingdom' },
  { label: 'Jungtinės Amerikos Valstijos', value: 'United States' },
  { label: 'Urugvajus', value: 'Uruguay' },
  { label: 'Uzbekistanas', value: 'Uzbekistan' },
  { label: 'Vanuatu', value: 'Vanuatu' },
  { label: 'Vatikanas', value: 'Vatican City' },
  { label: 'Venesuela', value: 'Venezuela' },
  { label: 'Vietnamas', value: 'Vietnam' },
  { label: 'Jemenas', value: 'Yemen' },
  { label: 'Zambija', value: 'Zambia' },
  { label: 'Zimbabvė', value: 'Zimbabwe' },
];
