/** A curated list of common job titles across departments/seniority levels
 * — used to give the Job Titles filter a pick-from list instead of pure
 * free typing. `label` is shown in Lithuanian; `value` is the English
 * title Apollo's API actually matches against (its global database is
 * indexed in English) — never translate `value`, only `label`. Apollo's
 * public API has no typeahead/suggestion endpoint for titles, so this is
 * a static, curated set rather than anything account- or API-derived —
 * the filter still accepts any custom typed value too, this list is a
 * starting point, not a cap. */
export const JOB_TITLES: Array<{ label: string; value: string }> = [
  // Executive
  { label: 'CEO', value: 'CEO' },
  { label: 'Generalinis direktorius', value: 'Chief Executive Officer' },
  { label: 'COO', value: 'COO' },
  { label: 'Operacijų direktorius', value: 'Chief Operating Officer' },
  { label: 'CFO', value: 'CFO' },
  { label: 'Finansų direktorius', value: 'Chief Financial Officer' },
  { label: 'CTO', value: 'CTO' },
  { label: 'Technologijų direktorius', value: 'Chief Technology Officer' },
  { label: 'CMO', value: 'CMO' },
  { label: 'Rinkodaros direktorius', value: 'Chief Marketing Officer' },
  { label: 'CRO', value: 'CRO' },
  { label: 'Pajamų direktorius', value: 'Chief Revenue Officer' },
  { label: 'CIO', value: 'CIO' },
  { label: 'Informacinių technologijų direktorius', value: 'Chief Information Officer' },
  { label: 'CHRO', value: 'CHRO' },
  { label: 'Personalo direktorius', value: 'Chief Human Resources Officer' },
  { label: 'CPO', value: 'CPO' },
  { label: 'Produkto direktorius', value: 'Chief Product Officer' },
  { label: 'Generalinio direktoriaus padėjėjas', value: 'Chief of Staff' },
  { label: 'Prezidentas', value: 'President' },
  { label: 'Viceprezidentas', value: 'Vice President' },
  { label: 'Pardavimų viceprezidentas', value: 'VP of Sales' },
  { label: 'Rinkodaros viceprezidentas', value: 'VP of Marketing' },
  { label: 'Inžinerijos viceprezidentas', value: 'VP of Engineering' },
  { label: 'Operacijų viceprezidentas', value: 'VP of Operations' },
  { label: 'Produkto viceprezidentas', value: 'VP of Product' },
  { label: 'Finansų viceprezidentas', value: 'VP of Finance' },
  { label: 'Klientų sėkmės viceprezidentas', value: 'VP of Customer Success' },
  { label: 'Personalo viceprezidentas', value: 'VP of Human Resources' },
  { label: 'Įkūrėjas', value: 'Founder' },
  { label: 'Bendraįkūrėjas', value: 'Co-Founder' },
  { label: 'Savininkas', value: 'Owner' },
  { label: 'Vykdantysis direktorius', value: 'Managing Director' },
  { label: 'Generalinis vadovas', value: 'General Manager' },
  { label: 'Partneris', value: 'Partner' },

  // Sales
  { label: 'Pardavimų vadovas', value: 'Head of Sales' },
  { label: 'Pardavimų direktorius', value: 'Sales Director' },
  { label: 'Pardavimų vadybininkas', value: 'Sales Manager' },
  { label: 'Pardavimų atstovas', value: 'Sales Representative' },
  { label: 'Klientų vadovas', value: 'Account Executive' },
  { label: 'Klientų vadybininkas', value: 'Account Manager' },
  { label: 'Verslo plėtros vadybininkas', value: 'Business Development Manager' },
  { label: 'Verslo plėtros atstovas', value: 'Business Development Representative' },
  { label: 'Pardavimų plėtros atstovas', value: 'Sales Development Representative' },
  { label: 'Regiono pardavimų vadybininkas', value: 'Regional Sales Manager' },
  { label: 'Vidinių pardavimų atstovas', value: 'Inside Sales Representative' },
  { label: 'Stambių klientų vadovas', value: 'Enterprise Account Executive' },
  { label: 'Pardavimų operacijų vadybininkas', value: 'Sales Operations Manager' },
  { label: 'Partnerių pardavimų vadybininkas', value: 'Channel Sales Manager' },
  { label: 'Pagrindinių klientų vadybininkas', value: 'Key Account Manager' },

  // Marketing
  { label: 'Rinkodaros vadovas', value: 'Head of Marketing' },
  { label: 'Rinkodaros direktorius', value: 'Marketing Director' },
  { label: 'Rinkodaros vadybininkas', value: 'Marketing Manager' },
  { label: 'Skaitmeninės rinkodaros vadybininkas', value: 'Digital Marketing Manager' },
  { label: 'Produkto rinkodaros vadybininkas', value: 'Product Marketing Manager' },
  { label: 'Turinio rinkodaros vadybininkas', value: 'Content Marketing Manager' },
  { label: 'Augimo rinkodaros vadybininkas', value: 'Growth Marketing Manager' },
  { label: 'Prekės ženklo vadybininkas', value: 'Brand Manager' },
  { label: 'Rinkodaros koordinatorius', value: 'Marketing Coordinator' },
  { label: 'Rinkodaros specialistas', value: 'Marketing Specialist' },
  { label: 'SEO specialistas', value: 'SEO Specialist' },
  { label: 'Socialinių tinklų vadybininkas', value: 'Social Media Manager' },
  { label: 'Paklausos generavimo vadybininkas', value: 'Demand Generation Manager' },
  { label: 'Komunikacijos vadybininkas', value: 'Communications Manager' },
  { label: 'Ryšių su visuomene vadybininkas', value: 'PR Manager' },

  // Engineering / Product / IT
  { label: 'Inžinerijos vadovas', value: 'Head of Engineering' },
  { label: 'Inžinerijos vadybininkas', value: 'Engineering Manager' },
  { label: 'Programinės įrangos inžinierius', value: 'Software Engineer' },
  { label: 'Vyresnysis programinės įrangos inžinierius', value: 'Senior Software Engineer' },
  { label: 'Vyriausiasis programinės įrangos inžinierius', value: 'Staff Software Engineer' },
  { label: 'Backend inžinierius', value: 'Backend Engineer' },
  { label: 'Frontend inžinierius', value: 'Frontend Engineer' },
  { label: 'Full Stack inžinierius', value: 'Full Stack Engineer' },
  { label: 'DevOps inžinierius', value: 'DevOps Engineer' },
  { label: 'Patikimumo inžinierius', value: 'Site Reliability Engineer' },
  { label: 'Kokybės užtikrinimo inžinierius', value: 'QA Engineer' },
  { label: 'Duomenų inžinierius', value: 'Data Engineer' },
  { label: 'Duomenų mokslininkas', value: 'Data Scientist' },
  { label: 'Mašininio mokymosi inžinierius', value: 'Machine Learning Engineer' },
  { label: 'Sprendimų architektas', value: 'Solutions Architect' },
  { label: 'Produkto vadybininkas', value: 'Product Manager' },
  { label: 'Vyresnysis produkto vadybininkas', value: 'Senior Product Manager' },
  { label: 'Produkto vadovas', value: 'Head of Product' },
  { label: 'Produkto savininkas', value: 'Product Owner' },
  { label: 'UX dizaineris', value: 'UX Designer' },
  { label: 'UI dizaineris', value: 'UI Designer' },
  { label: 'Produkto dizaineris', value: 'Product Designer' },
  { label: 'IT vadybininkas', value: 'IT Manager' },
  { label: 'IT direktorius', value: 'IT Director' },
  { label: 'Sistemų administratorius', value: 'Systems Administrator' },
  { label: 'Tinklų inžinierius', value: 'Network Engineer' },
  { label: 'Saugumo inžinierius', value: 'Security Engineer' },

  // Operations / Finance
  { label: 'Operacijų vadybininkas', value: 'Operations Manager' },
  { label: 'Operacijų direktorius', value: 'Operations Director' },
  { label: 'Operacijų vadovas', value: 'Head of Operations' },
  { label: 'Projektų vadovas', value: 'Project Manager' },
  { label: 'Programų vadovas', value: 'Program Manager' },
  { label: 'Tiekimo grandinės vadybininkas', value: 'Supply Chain Manager' },
  { label: 'Logistikos vadybininkas', value: 'Logistics Manager' },
  { label: 'Pirkimų vadybininkas', value: 'Procurement Manager' },
  { label: 'Finansų vadybininkas', value: 'Finance Manager' },
  { label: 'Finansų direktorius', value: 'Finance Director' },
  { label: 'Kontroleris', value: 'Controller' },
  { label: 'Finansų analitikas', value: 'Financial Analyst' },
  { label: 'Buhalteris', value: 'Accountant' },
  { label: 'Buhalterijos vadybininkas', value: 'Accounting Manager' },
  { label: 'Iždininkas', value: 'Treasurer' },

  // HR / People
  { label: 'Personalo vadovas', value: 'Head of HR' },
  { label: 'Personalo direktorius', value: 'HR Director' },
  { label: 'Personalo vadybininkas', value: 'HR Manager' },
  { label: 'Personalo verslo partneris', value: 'HR Business Partner' },
  { label: 'Talentų paieškos vadybininkas', value: 'Talent Acquisition Manager' },
  { label: 'Personalo atrankos specialistas', value: 'Recruiter' },
  { label: 'Personalo operacijų vadybininkas', value: 'People Operations Manager' },
  { label: 'Mokymų vadybininkas', value: 'Training Manager' },
  { label: 'Atlygio ir lengvatų vadybininkas', value: 'Compensation and Benefits Manager' },

  // Customer Success / Support
  { label: 'Klientų sėkmės vadovas', value: 'Head of Customer Success' },
  { label: 'Klientų sėkmės vadybininkas', value: 'Customer Success Manager' },
  { label: 'Klientų sėkmės direktorius', value: 'Customer Success Director' },
  { label: 'Klientų aptarnavimo vadybininkas', value: 'Customer Support Manager' },
  { label: 'Aptarnavimo specialistas', value: 'Support Specialist' },
  { label: 'Techninės pagalbos inžinierius', value: 'Technical Support Engineer' },
  { label: 'Diegimo vadybininkas', value: 'Implementation Manager' },
  { label: 'Adaptacijos specialistas', value: 'Onboarding Specialist' },

  // Other / General
  { label: 'Konsultantas', value: 'Consultant' },
  { label: 'Vyresnysis konsultantas', value: 'Senior Consultant' },
  { label: 'Analitikas', value: 'Analyst' },
  { label: 'Vyresnysis analitikas', value: 'Senior Analyst' },
  { label: 'Vadovo asistentas', value: 'Executive Assistant' },
  { label: 'Administracijos asistentas', value: 'Administrative Assistant' },
  { label: 'Biuro vadybininkas', value: 'Office Manager' },
  { label: 'Teisės patarėjas', value: 'Legal Counsel' },
  { label: 'Vyriausiasis teisės patarėjas', value: 'General Counsel' },
  { label: 'Direktorius', value: 'Director' },
  { label: 'Vyresnysis direktorius', value: 'Senior Director' },
  { label: 'Vadybininkas', value: 'Manager' },
  { label: 'Vyresnysis vadybininkas', value: 'Senior Manager' },
  { label: 'Koordinatorius', value: 'Coordinator' },
  { label: 'Specialistas', value: 'Specialist' },
  { label: 'Jaunesnysis specialistas', value: 'Associate' },
];
